#!/usr/bin/env zsh

# Pick changed files from the working tree. Useful when combined with other commands like `git add` or `vim`
git ls-files -mdo --exclude-standard | fzf --extended --multi --select-1 --exit-0
