#!/usr/bin/env zsh

# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
git tag --sort -version:refname |
fzf --height 50% --min-height 20 --border --bind ctrl-/:toggle-preview \
  --multi --preview-window right:70% \
  --preview 'git show --color=always {}'
