#!/usr/bin/env zsh

# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
git stash list |
fzf --height 50% --min-height 20 --border --bind ctrl-/:toggle-preview \
  --reverse -d: --preview 'git show --color=always {1}' |
cut -d: -f1

