#!/usr/bin/env zsh

# Pick changed files from the working tree. Useful when combined with other commands like `git add` or `vim`
# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
git -c color.status=always status --short |
fzf --height 50% --min-height 20 --border --bind ctrl-/:toggle-preview \
  --multi --ansi --nth 2..,.. \
  --preview 'git diff --color=always -- {-1} | (hash 2>/dev/null dne && delta || cat)' |
cut -c4- | sed 's/.* -> //'
