#!/usr/bin/env zsh

# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
git branch -a --color=always --sort=-committerdate | grep -v '/HEAD\s' |
fzf --height 50% --min-height 20 --border --bind ctrl-/:toggle-preview \
  --ansi --multi --preview-window right:70% \
  --preview 'git one --graph --color=always' |
sed 's/^..//' | cut -d' ' -f1 |
sed 's#^remotes/##'
