#!/usr/bin/env zsh

local uname=$(uname)
typeset -a stat_command
stat_command=("stat")
if [[ "$uname" == "Linux" ]]; then
    stat_command+=("-c" "%Y")
elif [[ "$uname" == "Darwin" ]]; then
    stat_command+=("-f" "%m")
fi

local template_modified=$("$stat_command[@]" git/gitconfig.template)
local installed_modified=$("$stat_command[@]" "${HOME}"/.gitconfig)
unset stat_command

if [[ "$template_modified" -lt "$installed_modified" ]]; then
    exit 0
fi

local git_credential="cache"
if [[ "$(uname -s)" == "Darwin" ]]; then
    git_credential="osxkeychain"
fi

local git_push_default="current"
local git_version="$(git --version | awk 'NR==1{print $3}')"
local git_major_version="${git_version:0:1}"
if [[ "$git_major_version" -ge 2 ]]; then
    git_push_default="simple"
fi

vared -p 'What is your GitHub author name? ' -c git_author
vared -p 'What is your GitHub author email? ' -c git_email

local git_signing_key="${HOME}/.ssh/id_ed25519.pub"
vared -p 'What is the path to your SSH public key for commit signing? ' -c git_signing_key

if [[ -f "$git_signing_key" ]]; then
    mkdir -p -- "${HOME}"/.ssh
    touch -- "${HOME}"/.ssh/allowed_signers
    local signer_line="${git_email} $(cat -- "$git_signing_key")"
    grep -qxF "$signer_line" "${HOME}"/.ssh/allowed_signers || echo "$signer_line" >>"${HOME}"/.ssh/allowed_signers
fi

sed -e "s/{AUTHOR_NAME}/$git_author/g" -e "s/{AUTHOR_EMAIL}/$git_email/g" -e "s/{GIT_CREDENTIAL_HELPER}/$git_credential/g" -e "s/{GIT_PUSH_DEFAULT}/$git_push_default/g" -e "s#{GIT_SIGNING_KEY}#$git_signing_key#g" git/gitconfig.template >git/gitconfig
