" .vimrc

" {{{ Vundle

" Required Vundle setup
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim
call g:vundle#begin()

Plugin 'gmarik/Vundle.vim'

" :Ack
Plugin 'mileszs/ack.vim'

" Better status line
Plugin 'bling/vim-airline'

" ga for character descriptions
Plugin 'tpope/vim-characterize'

" :Gdiff, :Gcommit, etc.
Plugin 'tpope/vim-fugitive'

" Markdown syntax
Plugin 'tpope/vim-markdown'

" Add support for github-style fenced codeblocks in markdown
Plugin 'jtratner/vim-flavored-markdown.git'

" Python syntax folding
Plugin 'tmhedberg/SimpylFold'

" Syntax, linting, etc.
Plugin 'scrooloose/syntastic'

" Clojure syntax
Plugin 'vim-scripts/VimClojure'

" Solarized theme
Plugin 'altercation/vim-colors-solarized'

" Javascript syntax
Plugin 'jelera/vim-javascript-syntax'

" JSON syntax highlighting
Plugin 'leshill/vim-json'

" Comment with gc
Plugin 'tpope/vim-commentary'

" Amazing mappings
Plugin 'tpope/vim-unimpaired'

" Repeat things
Plugin 'tpope/vim-repeat'

" JSON pretty printing with gqaj
Plugin 'tpope/vim-jdaddy'

" git runtime files - highlight git config, commit, etc.
Plugin 'tpope/vim-git'

" Inline git status
Plugin 'airblade/vim-gitgutter'

" Coffeescript
Plugin 'kchmck/vim-coffee-script'

" YouCompleteMe
Plugin 'Valloric/YouCompleteMe'

" TernJS
Plugin 'marijnh/tern_for_vim'

" Open current Markdown buffer in Marked2
Plugin 'itspriddle/vim-marked'

" Better rainbow parens
Plugin 'luochen1990/rainbow'

" iTerm2 and tmux integration
Plugin 'sjl/vitality.vim'

" Lint vimscript with vint; requires vint: pip install vim-vint
Plugin 'todesking/vint-syntastic'

" netrw improvements
Plugin 'tpope/vim-vinegar'

" argument manipulation
Plugin 'PeterRincker/vim-argumentative'

" manipulate delimiters
Plugin 'tpope/vim-surround'

" even better (and consistent) fuzzy finding
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'

call g:vundle#end()

filetype plugin indent on
syntax enable

" }}}
" {{{ Setup

" Set the terminal font encoding
set encoding=utf-8
scriptencoding utf-8
set termencoding=utf-8

" Manage multiple buffers
set hidden

" Map leader to <space>
let g:mapleader = ' '
let g:maplocalleader = ' '

" More frequent updates for, e.g. signs.
set updatetime=750

" }}}
" {{{ Ack
" Skip normal config, show filenames, no color, one result per line, show column numbers, smart case
let g:ackprg='ack --noenv -H --nocolor --nogroup --column --smart-case --after=0 --before=0'

" }}}
" {{{ Airline
" No separators between sections
let g:airline_left_sep = ''
let g:airline_right_sep = ''

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.whitespace = 'Ξ'
let g:airline_symbols.readonly = '🔒'

" Modified theme
" * status same color as tab line
" * inactive bg different than status and ruler
function! g:AirlineThemeModified(palette)
    if g:airline_theme ==? 'solarized'
        let a:palette.normal_modified.airline_c =  ['#eee8d5', '#b58900', 254, 136, 'bold']
        let a:palette.insert_modified.airline_c =  ['#eee8d5', '#b58900', 254, 136, 'bold']
        let a:palette.visual_modified.airline_c =  ['#eee8d5', '#b58900', 254, 136, 'bold']
        let a:palette.inactive_modified.airline_c =['#b58900', '', 136, '', 'bold']

        for l:colors in values(a:palette.inactive)
            let l:colors[2] = 241
            let l:colors[3] = 235
        endfor
    endif
endfunction
let g:airline_theme_patch_func = 'g:AirlineThemeModified'

" Enable buffers and numbers in the tab bar
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#buffer_min_count = 2

" No line number in status; just column and percentage
let g:airline_section_z = g:airline#section#create(['%2v'.g:airline_symbols.space, '%3p%%'])

" No need for mode (or crypt, paste, iminsert, etc.) because of showmode
" No need for file encoding or format
let g:airline#extensions#default#layout = [
    \ [ 'b', 'c' ],
    \ [ 'z', 'warning']
\ ]

" }}}
" {{{ Autocommands
if has('autocmd')
    " Clear existing autocommands before defining them, in case this file is loaded again
    autocmd!

    augroup last_cursor
        autocmd!

        " Jump to last cursor position unless it's invalid or in an event handler or
        " a git commit
        autocmd BufReadPost *
          \ if &filetype !~ '^git\c' && line("'\"") > 0 && line("'\"") <= line('$') |
          \   exe 'normal! g`"' |
          \ endif
    augroup END

    augroup cursor_highlight
        autocmd!

        " Only show cursorline in active windows
        autocmd WinLeave * set nocursorline colorcolumn=""
        autocmd WinEnter * set cursorline colorcolumn=+1
    augroup END

    augroup coffescript
        autocmd!

        " Automatically set coffeescript filetype; necessary because of some vundle filetype issue
        autocmd BufNewFile,BufRead *.coffee setlocal filetype=coffee
    augroup END

    augroup markdown
        autocmd!

        " Automatically use github-flavored markdown
        autocmd BufNewFile,BufRead *.md,*.markdown setlocal filetype=ghmarkdown
    augroup END
endif

" }}}
" {{{ Backups
" Skip backup entirely. It's annoying.
set nobackup
if has('writebackup')
    set nowritebackup
endif

" }}}
" {{{ Commands
" Note that these options don't really matter when using vim-powerline.
if has('cmdline_info')
    " Show line and column information
    set ruler

    " Show command information in the status
    set showcmd

    " Show which mode we're in
    set showmode
endif

" }}}
" {{{ Diff
set diffopt+=vertical
" }}}
" {{{ Folding
" Fold with triple curly braces, fill with spaces
if has('folding')
    set foldenable
    set foldmethod=marker
    set foldopen=hor,search,tag,undo
    set fillchars=diff:\ ,fold:\ ,vert:\
endif

" }}}
" {{{ Formatting
" Auto indent new lines
set autoindent

" Show matching braces
set showmatch

" Spacing and tabbing
" Use shiftwidth and tabstop smartly
set smarttab

" Spaces
set expandtab

" Tab width
set tabstop=4
set softtabstop=4
set shiftwidth=4

set textwidth=100

" Don't wrap text
set nowrap

" Highlight the first column after the text width
if exists('&colorcolumn')
    set colorcolumn=+1
endif

" From the Vim docs:
" t   Auto-wrap text using textwidth
"
" c   Auto-wrap comments using textwidth, inserting the current comment
"     leader automatically.
"
" r   Automatically insert the current comment leader after hitting
"     <Enter> in Insert mode.
"
" o   Automatically insert the current comment leader after hitting 'o' or
"     'O' in Normal mode.
"
" n   When formatting text, recognize numbered lists.  This actually uses
"     the 'formatlistpat' option, thus any kind of list can be used.  The
"     indent of the text after the number is used for the next line.  The
"     default is to find a number, optionally followed by '.', ':', ')',
"     ']' or '}'.  Note that 'autoindent' must be set too.  Doesn't work
"     well together with "2".
"     Example:
"         1. the first item
"            wraps
"         2. the second item
set formatoptions+=t,c,r,o,n

" Delete comment character when joining commented lines
if v:version > 703 || v:version == 703 && has('patch541')
  set formatoptions+=j
endif

" Use only 1 space after "." when joining lines instead of 2
set nojoinspaces

augroup vimrc
    autocmd!

    autocmd FileType xhtml,xml,html set textwidth=0
    autocmd FileType make set noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
    autocmd FileType markdown set textwidth=0 wrap linebreak wrapmargin=0
    autocmd FileType clojure set tabstop=2 softtabstop=2 shiftwidth=2
    autocmd FileType yaml set tabstop=2 softtabstop=2 shiftwidth=2
augroup END

" }}}
" {{{ Fugitive
nnoremap <leader>gb :Gblame<cr>
nnoremap <leader>gc :Gcommit<cr>
nnoremap <leader>gd :Gdiff<cr>
nnoremap <leader>gl :Glog<cr>
nnoremap <leader>gp :Git push<cr>
nnoremap <leader>gs :Git status -sb<cr>

" }}}
" {{{ fzf
nnoremap <silent> <leader><leader> :Files<cr>
nnoremap <silent> <leader><Enter> :Buffers<cr>

" }}}
" {{{ git-gutter
" Escape grep so we don't have color codes
let g:gitgutter_escape_grep = 1

" Ignore whitespace (we have other plugins for that)
let g:gitgutter_diff_args = '-w'

" Don't map any keys by default
let g:gitgutter_map_keys = 0

nmap ]h <Plug>GitGutterNextHunk
nmap [h <Plug>GitGutterPrevHunk
nnoremap <leader>hs <Plug>GitGutterStageHunk
nnoremap <leader>hr <Plug>GitGutterRevertHunk

" }}}
" {{{ History
" Command history
set history=1000

" }}}
" {{{ Key remaps
" Completion
inoremap <Nul> <C-X><C-P>

" Edit and source this file
nmap <silent> <leader>ev :split $MYVIMRC<CR>
nmap <silent> <leader>sv :source $MYVIMRC<CR>

" Annoyances

" No arrow keys
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

" Tab navigation
" nmap <F4> :tabnew<CR>
" nmap <F5> :tabp<CR>
" nmap <F6> :tabn<CR>

" Bind dumb uppercase commands to their useful lowercase equivalents
if has('user_commands')
    command! -bang E e<bang>
    command! -bang Q q<bang>
    command! -bang W w<bang>
    command! -bang QA qa<bang>
    command! -bang Qa qa<bang>
    command! -bang Wa wa<bang>
    command! -bang WA wa<bang>
    command! -bang Wq wq<bang>
    command! -bang WQ wq<bang>
endif

" Make Y act like other uppercase commands
nnoremap Y y$

" Disable going to Ex mode
noremap Q <nop>

" Remove annoying F1 help; use :help instead
noremap <F1> <nop>

" No man pages because I don't write C or many shell scripts
noremap K <nop>

" Shortcuts for diff
nnoremap <leader>dg :diffget<cr>
nnoremap <leader>dp :diffput<cr>
" }}}
" {{{ Line Numbers
" Show line numbers
set number
if exists('&relativenumber')
    set relativenumber
endif

" }}}
" {{{ List
" Toggle invisibles, hide by default
set nolist
set listchars=eol:¬,tab:▸·,trail:·,nbsp:_,extends:❯,precedes:❮
nnoremap <leader>l :set list!<CR>

" }}}
" {{{ Matching
" Enable extended % matching
silent! runtime macros/matchit.vim

" }}}
" {{{ Messages
" Shorten a lot of notifications and suppress the splash screen
set shortmess+=aI

" }}}
" {{{ Rainbow
let g:rainbow_active = 1

let g:rainbow_conf = {
    \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
    \   'ctermfgs': ['darkblue', 'darkyellow', 'darkmagenta', 'darkred', 'red', 'blue', 'yellow', 'magenta', 'cyan', 'lightblue', 'lightyellow', 'lightmagenta', 'lightcyan'],
    \   'operators': '_,_',
    \   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
    \   'separately': {
    \       '*': {},
    \       'tex': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
    \       },
    \       'lisp': {
    \           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
    \       },
    \       'vim': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
    \       },
    \       'html': {
    \           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
    \       },
    \       'css': 0,
    \   }
    \}
" }}}
" {{{ Scrolling
" Scrolling context; lines/columns of buffer while scrolling
set scrolloff=3
set sidescrolloff=5

" Scrolling speed
nnoremap <C-e> 5<C-e>
nnoremap <C-y> 5<C-y>

" }}}
" {{{ Search
if has('extra_search')
    " Highlight searches
    set hlsearch
    nnoremap <leader>h :nohlsearch<CR>

    " Be smart about searching case-sensitively
    set smartcase
    set ignorecase

    " Search as you type
    set incsearch
    nnoremap <leader>i :set incsearch!<CR>

    " Wrap around the file when searching
    set wrapscan
endif

" }}}
" {{{ Spelling
if has('spell')
    set spelllang=en_us
    nnoremap <leader>sp :set spell!<CR>
endif

" }}}
" {{{ Splits

" Intuitive split locations
set splitbelow
set splitright

" }}}
" {{{ Status line
" Always show the status line
set laststatus=2
" Disable this status line when using Powerline
"set statusline=%-3.3n\ %f%(\ %r%)%(\ %#WarningMsg#%m%0*%)%=(%l/%L,\ %c)\ %P\ [%{&encoding}:%{&fileformat}]%(\ %w%)\ %y

" }}}
" {{{ Swap
" Turn swap off
set noswapfile
set updatecount=0

" }}}
" {{{ Syntastic
" Use jshint (uses ~/.jshintrc)
let g:syntastic_javascript_checkers = ['eslint', 'jscs']
let g:syntastic_javascript_eslint_args = '--rulesdir "$HOME"/.eslint_rules'

" Use flake8
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_args = '--ignore="E501,E302,E261,E701,E241,E126,E127,E128,E121,W801"'

" Disable shellcheck for zsh
let g:syntastic_zsh_checkers = ['zsh']

" Use vint for vim style
let g:syntastic_vim_checkers=['vint']

" On by default, turn it off for html
let g:syntastic_mode_map = { 'mode': 'active',
                           \ 'active_filetypes': [],
                           \ 'passive_filetypes': ['html'] }

" Better :sign interface symbols
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '!'
let g:syntastic_style_error_symbol = '☡'
let g:syntastic_style_warning_symbol = '¡'

" Check on buffer open
let g:syntastic_check_on_open = 1

" Always put errors in the location list
let g:syntastic_always_populate_loc_list = 1

" Aggregate errors for multiple checkers
let g:syntastic_aggregate_errors = 1

" Don't check on write+quit
let g:syntastic_check_on_wq = 0
" }}}
" {{{ Terminal

" Better redrawing for large files
set ttyfast

" Disable the vbell
set visualbell t_vb=

" }}}
" {{{ Undo
" -- see http://amix.dk/blog/post/19548
if has('persistent_undo')
    set undodir=~/.vim/undodir
    set undofile

    " max changes that can be undone
    set undolevels=1000

    " max lines to save for undo on buffer reload
    set undoreload=10000
endif

" }}}
" {{{ Utility
" Respect vim modelines
set modeline

" Use the file's name in the title
set title

" Highlight the line the cursor is on
set cursorline

" Let backspace do what it's supposed to: allow backspace over indent, eol, and start of an insert
set backspace=indent,eol,start

" Reuse open buffers and tabs
set switchbuf=useopen,usetab

" }}}
" {{{ Wildmenu
if has('wildmenu')
    " Bash-like tab completion for commands
    set wildmenu
    set wildmode=longest:list
    set wildchar=<Tab>
    if has('wildignore')
        set wildignore+=*.a,*.o,*.pyc,.DS_Store
        set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
        set wildignore+=*~,*.swp,*.tmp
    endif
    if exists('&wildignorecase')
        set wildignorecase
    endif
endif

" }}}
" {{{ Windows
" Split windows below and right -- default is above and left, which can be disorienting
set splitbelow splitright

" Better window management and navigation
map <leader>w <C-w>w
map <leader>W <C-w>W
map <leader>_ <C-w>_

noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
" }}}

" {{{ Epilog
" Turn syntax on after everything else
syntax on

" {{{ Colors
set background=dark

let g:solarized_termtrans = 1
let g:solarized_underline = 0
silent! colorscheme solarized

hi Folded term=standout ctermfg=3 ctermbg=none

highlight link SignColumn LineNr
highlight link GitGutterAdd DiffAdd
highlight link GitGutterChange DiffChange
highlight link GitGutterDelete DiffDelete
highlight link GitGutterChangeDelete DiffDelete

" }}}
" }}}
