#!/usr/bin/env zsh

TMUX_PLUGIN_DIR="$HOME"/.tmux/plugins
TPM_DIR="$TMUX_PLUGIN_DIR/tpm"

if [ ! -d "$TPM_DIR" ]; then
    git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
else
    cd "$TPM_DIR" || exit
    git pull origin master
fi
