#!/usr/bin/env zsh

# Clone oh-my-zsh, but only if it doesn't exist yet
if [ ! -d "$HOME"/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
