#!/usr/bin/env zsh

# Clone oh-my-zsh, but only if it doesn't exist yet
if [ ! -d "$HOME"/.oh-my-zsh ]; then
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
fi

if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/fzf-tab ]; then
    git clone https://github.com/Aloxaf/fzf-tab "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/fzf-tab
fi
if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/fast-syntax-highlighting ]; then
    git clone https://github.com/zdharma/fast-syntax-highlighting.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/fast-syntax-highlighting
fi
if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
fi
if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-better-npm-completion ]; then
    git clone https://github.com/lukechilds/zsh-better-npm-completion "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-better-npm-completion
fi
if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/jj-zsh-vcs-info ]; then
    git clone https://github.com/joeshaw/jj-zsh-vcs-info.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/jj-zsh-vcs-info
fi
