# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=""

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Highlight all available matches
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git lein osx rake ant colored-man-pages colorize zsh-syntax-highlighting history-substring-search)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# `cd $0` if no other match; e.g. > code => > cd code
setopt AUTO_CD

# Allow comments in interactive mode, i.e. on the command line
setopt INTERACTIVE_COMMENTS

# Bigger history
export HISTSIZE=65535
export SAVEHIST=$HISTSIZE
# Save timestamps with history
setopt EXTENDED_HISTORY
# Ignore duplicate entries; older dupes are removed
setopt HIST_IGNORE_DUPS
# Ignore commands that begin with a space; useful for sensitive information
setopt HIST_IGNORE_SPACE

# -R -- properly display color escape sequences (was on by default; necessary to include when changing)
# -s -- squeeze consecutive blank lines into one line
# -X -- don't clear the screen on exit
# -F -- immediately quit if the output fits on one screen; useful for `git diff` and short man pages
export LESS="-R -s -X -F"

# Use vim if it's available
hash vim 2>/dev/null && export EDITOR=vim
bindkey -v

# Explicit JAVA_HOME, for OS X
[[ -x /usr/libexec/java_home ]] && export JAVA_HOME="$(/usr/libexec/java_home)"

# Path
# Explicitly add /usr/local/bin to PATH first
typeset -U path
path=(/usr/local/bin "$path[@]")

if [[ -d "$HOME"/.zshrc.d ]]; then
    for config in "$HOME"/.zshrc.d/*.zsh; do
        source "$config"
    done
fi
unset -v config

# add cwd and ~/.local/bin after including other config
path=(. "$HOME"/.local/bin "$path[@]")

# do this last in case any scripts touch the path
export PATH
