# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/tupton/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Highlight all available matches
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root line)

# nvm options
# Lazy load nvm when running nvm, node, npm instead of on shell init
NVM_LAZY_LOAD=true
# Also lazy load when running vim
NVM_LAZY_LOAD_EXTRA_COMMANDS=('vim')
# Automatically use the right version of node when there's an .nvmrc
NVM_AUTO_USE=true

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git macos colored-man-pages history-substring-search zsh-nvm zsh-better-npm-completion fzf-tab zsh-autosuggestions fast-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Bigger history
export HISTSIZE=65535
export SAVEHIST=$HISTSIZE

# -R -- properly display color escape sequences (was on by default; necessary to include when changing)
# -s -- squeeze consecutive blank lines into one line
# -X -- don't clear the screen on exit
# -F -- immediately quit if the output fits on one screen; useful for `git diff` and short man pages
export LESS="-R -s -X -F"

# Use vim if it's available
hash vim 2>/dev/null && export EDITOR=vim
# ...but prefer nvim
hash nvim 2>/dev/null && export EDITOR=nvim
bindkey -v

# Explicit JAVA_HOME, for OS X
[[ -x /usr/libexec/java_home ]] && export JAVA_HOME="$(/usr/libexec/java_home 2>/dev/null)"

# Explicitly set GPG_TTY for gpg-agent so git can prompt for passphrase
export GPG_TTY=$(tty)

# Path
typeset -U path

# Explicitly add /usr/local/bin and sbin to PATH first
path=(/usr/local/bin /usr/local/sbin "$path[@]")

# path modifications for homebrew
if [ -e /usr/local/bin/brew ]; then
  eval $(/usr/local/bin/brew shellenv)
fi
if [ -e /opt/homebrew/bin/brew ]; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi
if hash brew 2>/dev/null; then
    prefix="$(brew --prefix)"
    path=( "$prefix"/opt/ruby/bin \
        "$prefix"/opt/perl/bin \
        "$prefix"/opt/php/bin \
        "$prefix"/opt/gnu-sed/libexec/gnubin \
        "$path[@]")

    if [ -z "$CFG_EXCLUDE_HOMEBREW_PYTHON" ]; then
        path=( "$prefix"/opt/python/bin \
          "$prefix"/opt/python/libexec/bin \
          "$path[@]")
    fi
fi

# Rust path
if [ -d ~/.cargo/bin ]; then
  path=(~/.cargo/bin "$path[@]")
fi

# Go path
if hash go 2>/dev/null; then
    GOPATH=$HOME/go
    path=( $GOPATH/bin "$path[@]")
fi

# Yarn path
if hash yarn 2>/dev/null; then
  path=( $HOME/.yarn/bin $HOME/.config/yarn/global/node_modules/.bin "$path[@]")
fi

# Deno path
if hash deno 2>/dev/null; then
    path=( $HOME/.deno/bin "$path[@]")
fi

if [[ -d "$HOME"/.zshrc.d ]]; then
    for config in "$HOME"/.zshrc.d/*.zsh; do
        source "$config"
    done
fi
unset -v config

# add cwd and ~/.local/bin after including other config
path=(. "$HOME"/.local/bin "$path[@]")

# do this last in case any scripts touch the path
# path=( ${(u)^path:A} )
export PATH
